### ISSUE TITLE
Compile warning: FCVAR_PLUGIN is marked as deprecated

### ISSUE THREAD

**Issue by phorcep** [GameConnect/sourcebansv1#13]
When compiling sourcebans.sp with SourceMod 1.8.0:

`sourcebans.sp(145) : warning 234: symbol "FCVAR_PLUGIN" is marked as deprecated: No logic using this flag ever existed in a released game. It only ever appeared in the first hl2sdk.`

**Comment by peace-maker** [comment]
Thanks, removed.

**Comment by FZDNSZYT** [comment]
Also ask how to solve this type of error

**Comment by peace-maker** [comment]
Remove the `FCVAR_PLUGIN` from the CreateConvar call in the plugin.
