### ISSUE TITLE
SourceBans.net gone?

### ISSUE THREAD

**Issue by Mecha-Weasel** [GameConnect/sourcebansv1#14]
I've noticed references to SourceBans.net in the AlliedMods forums, etc. saying to go there for documentation and such.  However, SourceBans.net appears to be off-line? = like maybe expired and not renewed? or maybe just didn't renew the hosting?

**Comment by psychonic** [comment]
It's gone.

**Comment by peace-maker** [comment]
I've put up a redirect for now.
